version: '3.7'
services:
  db:
    image: postgres:12.2
    restart: always
    networks:
      spring-postgres-network:
        aliases:
          - db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      spring-postgres-network:
        aliases:
          - app
networks:
  spring-postgres-network:





