version: '3.1'
services:
  db:
    image: postgres:12.2
    #    container_name: db
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
  app:
#    container_name: app-springboot-postgresql
#    image: app-springboot-postgresql
    image: springapp:latest
#    environment: 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
    network_mode: bridge
    ports:
      - 8080:8080
    depends_on:
      - db







