version: '3.7'
services:
  db1:
    image: postgres:12.2
    restart: always
    networks:
      spring-postgres-network:
        aliases:
          - db1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
  app:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db1
    networks:
      spring-postgres-network:
        aliases:
          - app
networks:
  spring-postgres-network:





