spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db1:5432/test1
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
  flyway:
    url: jdbc:postgresql://db1:5432/test1
    user: postgres
    password: root
    baseline-on-migrate: true
    enabled: true
server:
  port: 8081