--
-- CREATE SEQUENCE hibernate_sequence;
--
-- create table  human
-- (
--     id int8 NOT NULL DEFAULT nextval('hibernate_sequence'),
--     age  int4 not null,
--     name varchar(255) not null,
--     primary key (id)
-- );


DROP SEQUENCE IF EXISTS hibernate_sequence;
CREATE SEQUENCE hibernate_sequence
  START 1
  INCREMENT 1;


CREATE TABLE human (
  id   int8 generated by default as identity,
  age  int4,
  name varchar(255),
  primary key (id)
);


CREATE TABLE point
(
  id          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  coordinates VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE attribute
(
  id   int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  PRIMARY KEY (id)
);


CREATE TABLE point_attribute_value
(
  point_id     int8 NOT NULL REFERENCES point (id),
  attribute_id int8 NOT NULL REFERENCES attribute (id),
  value        VARCHAR(255),
  PRIMARY KEY (point_id, attribute_id)
)